ALTER TABLE applications ADD COLUMN IF NOT EXISTS risk_override_tier TEXT;

ALTER TABLE monitoring ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'ACTIVE';
ALTER TABLE monitoring ADD COLUMN IF NOT EXISTS next_review_at TIMESTAMPTZ;

ALTER TABLE contracts ADD COLUMN IF NOT EXISTS coverage_start TIMESTAMPTZ;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS coverage_end TIMESTAMPTZ;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS coverage_description TEXT;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS coverage_limit TEXT;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS deductible TEXT;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS premium TEXT;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS payment_frequency TEXT;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS insurer TEXT;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS insurer_address TEXT;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS policyholder_address TEXT;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS dob DATE;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS sumsub_verification_id TEXT;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS sumsub_status TEXT;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS sumsub_verified_at TIMESTAMPTZ;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS monitoring_frequency TEXT;