ALTER TABLE applications
  ADD COLUMN IF NOT EXISTS external_applicant_id TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS risk_tier TEXT,
  ADD COLUMN IF NOT EXISTS monitoring_frequency TEXT,
  ADD COLUMN IF NOT EXISTS customer_id INTEGER,
  ADD COLUMN IF NOT EXISTS contract_id INTEGER,
  ADD COLUMN IF NOT EXISTS risk_score INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS decision_status TEXT,
  ADD COLUMN IF NOT EXISTS compliance_status TEXT,
  ADD COLUMN IF NOT EXISTS policy_status TEXT;

ALTER TABLE customers ADD COLUMN IF NOT EXISTS risk_score INTEGER DEFAULT 0;
